name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features postgres --locked
      - name: Migrate database
        run: sqlx database create && sqlx migrate run
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/newsletter
      - name: Run tests
        run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features postgres --locked
      - name: Migrate database
        run: sqlx database create && sqlx migrate run
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/newsletter
      - name: Linting
        run: cargo clippy -- -D warnings
